plugins:
  encrypt_enabled:
    client: true
    default: true
    refresh: true
  auto_enable_encrypt:
    client: true
    default: false
    refresh: true
  encrypt_groups:
    default: ""
    client: true
    type: list
